require('config.nvimtree')
require('config.colorscheme')
require('config.utils')
require('config.autocommands')
require('config.autopairs')
require('config.autotag')
require('config.barbar')
require('config.closetag')
require('config.comment')
require('config.compe')
require('config.dashboard')
require('config.emmet')
require('config.far')
require('config.floaterm')
require('config.galaxyline')
require('config.gitsigns')
require('config.quickscope')
require('config.rainbow')
require('config.refactor')
require('config.rnvimr')
require('config.telescope')
require('config.treesitter')
require('config.vsnip_snippet')
require('config.whichkey')

require('config.lsp')

vim.cmd('source ~/.config/nvim/vimscript/functions.vim')
