require("config.nvimtree")
require("config.colorscheme")
require("config.treesitter")
require("config.colorizer")
require("config.bufferline")
require("config.lualine_nvim")
require("config.gps")
require("config.floaterm")
require("config.rnvimr")
require("config.cmp")
require("config.escape")
require("config.comment")
require("config.gitsigns")
require("config.telescope")
require("config.indent_blankline")
require("config.dashboard")
require("config.autopairs")
require("config.surround")
-- require('config.trouble')

require("config.lsp")
require("config.whichkey")
