require('config.lsp.lua-ls')
-- require('config.lsp.json-ls')
require('config.lsp.pyright-ls')
require('config.lsp.java-ls')
require('config.lsp.efm-ls')
require('config.lsp.efm-ls')
require('config.lsp.tsserver-ls')
require('config.lsp.omnisharp-ls')
