require('config.lsp.lua-ls')
-- require('config.lsp.json-ls')
require('config.lsp.pyright-ls')
require('config.lsp.java-ls')
-- require('config.lsp.java-jdtls')
require('config.lsp.tsserver-ls')
-- require('config.lsp.omnisharp-ls')
require('config.lsp.bash-ls')
require('config.lsp.css-ls')
require('config.lsp.haskell-ls')
require('config.lsp.efm-ls')
